//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysGestionTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignUpTbl
    {
        public int Id_utilisateur { get; set; }
        public string nom { get; set; }
        public string e_mail { get; set; }
        public string MotDePasse { get; set; }
    }
}
